export const mockData = [
  {
    incidentID: "1",
    incidentTitle: "Burglary",
    witnessName: "Charlie White",
    offenderName: "Tracy A",
    date: "2023-03-22",
    description:
      "Charlie White reported a burglary at the Elmwood Shopping Center on March 22nd, 2023. Surveillance cameras captured an individual, identified as Tracy A, breaking into a jewelry store after hours and making off with various high-value items. Mall security and local police are currently collaborating to find Tracy and recover the stolen items.",
    incidentCategory: "Theft",
    attachedFile:
      "https://dm0qx8t0i9gc9.cloudfront.net/thumbnails/video/H5BOVymHiplawzr0/videoblocks-cctv-camera-monitor-in-the-mall-the-screen-is-divided-into-4-parts-system-of-safety-theft-and-terrorism-prevention_rhbhu5-zbb_thumbnail-1080_01.png",
    status: "Open",
    severity: "High",
  },
  {
    incidentID: "2",
    incidentTitle: "Vandalism",
    witnessName: "Hannah Red",
    offenderName: "Oscar D",
    date: "2023-05-30",
    description:
      "On May 30th, 2023, Hannah Red noticed graffiti sprawled across the walls of the Valley Mall's food court. The distinct style pointed to Oscar D, a known local vandal. The mall management has since initiated cleanup efforts and increased security patrols in the area, ensuring such incidents don't recur.",
    incidentCategory: "Other",
    attachedFile:
      "https://dm0qx8t0i9gc9.cloudfront.net/thumbnails/video/H5BOVymHiplawzr0/videoblocks-cctv-camera-monitor-in-the-mall-the-screen-is-divided-into-4-parts-system-of-safety-theft-and-terrorism-prevention_rhbhu5-zbb_thumbnail-1080_01.png",
    status: "Open",
    severity: "Low",
  },
  {
    incidentID: "3",
    incidentTitle: "Disturbance",
    witnessName: "John Doe",
    offenderName: "Victor X",
    date: "2022-10-05",
    description:
      "John Doe recounted a significant disturbance at the Crestwood Plaza on October 5th, 2022. Victor X was seen shouting at store employees, causing panic among shoppers. Mall security was called in, and Victor was escorted out. The motive behind Victor's aggressive behavior is still under investigation.",
    incidentCategory: "Physical",
    attachedFile:
      "https://dm0qx8t0i9gc9.cloudfront.net/thumbnails/video/H5BOVymHiplawzr0/videoblocks-cctv-camera-monitor-in-the-mall-the-screen-is-divided-into-4-parts-system-of-safety-theft-and-terrorism-prevention_rhbhu5-zbb_thumbnail-1080_01.png",
    status: "Open",
    severity: "Low",
  },
  {
    incidentID: "4",
    incidentTitle: "Fraud",
    witnessName: "Alice Johnson",
    offenderName: "Samuel B",
    date: "2023-04-12",
    description:
      "Alice Johnson fell victim to a credit card skimming scam at the Grandview Shopping Center on April 12th, 2023. While using an ATM, she noticed suspicious activities and later discovered unauthorized transactions. Samuel B has been identified from surveillance footage as the person installing the skimming device.",
    incidentCategory: "Theft",
    attachedFile: null,
    status: "Resolved",
    severity: "High",
  },
  {
    incidentID: "5",
    incidentTitle: "Vandalism",
    witnessName: "Edward Blue",
    offenderName: "Oscar D",
    date: "2023-02-26",
    description:
      "Edward Blue reported vandalism at the Lakeside Mall's parking area on February 26th, 2023. Several cars, including Edward's, had their tires slashed. CCTV footage has shown Oscar D lingering suspiciously around the cars during the time of the incident.",
    incidentCategory: "Harassment",
    attachedFile: null,
    status: "Open",
    severity: "Low",
  },
  {
    incidentID: "6",
    incidentTitle: "Assault",
    witnessName: "Bob Brown",
    offenderName: "Rachel C",
    date: "2023-05-05",
    description:
      "A scuffle broke out in the food court of Meadowbrook Mall on May 5th, 2023. Bob Brown, an onlooker, described Rachel C initiating a physical confrontation with another patron over a seating dispute. The incident left many shoppers distressed, and mall security intervened swiftly.",
    incidentCategory: "Physical",
    attachedFile: null,
    status: "Open",
    severity: "High",
  },
  {
    incidentID: "7",
    incidentTitle: "Burglary",
    witnessName: "Fiona Black",
    offenderName: "Mike F",
    date: "2022-12-12",
    description:
      "On December 12th, 2022, Fiona Black reported a break-in at the tech store she manages in Uptown Shopping Plaza. High-end gadgets were stolen, and Mike F was identified as the potential perpetrator from the security tapes. Enhanced security protocols have since been introduced in the plaza.",
    incidentCategory: "Theft",
    attachedFile: null,
    status: "Denied",
    severity: "High",
  },
  {
    incidentID: "8",
    incidentTitle: "Theft",
    witnessName: "Jane Smith",
    offenderName: "",
    date: "2023-01-26",
    description:
      "During a busy shopping day at Willowbrook Center on January 26th, 2023, Jane Smith realized her handbag was stolen from her shopping cart. A review of the CCTV footage pointed to Rachel C discreetly taking the bag and swiftly leaving the scene.",
    incidentCategory: "Theft",
    attachedFile: null,
    status: "Open",
    severity: "High",
  },
  {
    incidentID: "9",
    incidentTitle: "Theft",
    witnessName: "Charlie White",
    offenderName: "",
    date: "2023-05-27",
    description:
      "An outdoor promotional event at Sunridge Mall on May 27th, 2023, was disrupted when several merchandise items went missing. Charlie White noticed Victor X acting suspiciously and informed mall security. Investigations are underway to determine the extent of the theft.",
    incidentCategory: "Theft",
    attachedFile: null,
    status: "Resolved",
    severity: "Medium",
  },
  {
    incidentID: "10",
    incidentTitle: "Burglary",
    witnessName: "Alice Johnson",
    offenderName: "",
    date: "2023-08-05",
    description:
      "On August 5th, 2023, a boutique in Eastwood Mall reported a burglary. Alice Johnson, the store manager, discovered the back storeroom broken into and several designer outfits missing. Nina E, caught on camera, is the prime suspect in this theft, and the search for her is ongoing.",
    incidentCategory: "Theft",
    attachedFile: null,
    status: "Denied",
    severity: "Medium",
  },
];
